pygments: true
paginate: 10
prose:
  rooturl: "_posts
  metadata:
    "_posts":
      author: "Your name, uppercased, spaced"
      category: "Article category"
      symmary: "A short (<= 3 lines) summary that best describes your article"
      
